language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: true

before_script:
  - psql template1 -f db/create_schema.ddl -U postgres

# Command to install dependencies
install: "pip install -r requirements/travis.txt"

# Command to setup Django, database, and run tests
script:
  - (cd example_site/settings/; ln -s travis.py local.py)
  - python manage.py migrate
  - make tests

after_success:
  - coveralls 
